title: 'Public Service Week 2019'
description: Description
url: 'https://www.publicserviceweek.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css

collections:
    events:
        output: true
    exclusives:
        output: true
    CF-test:
        output: true
    lishi-test:
        output: true
    nazurah-pste:
        output: true
    xueyan:
        output: true
    yusri-test:
        output: true

resources_name: news
favicon: /images/PSW_Logo.png
google-analytics: UA-40876833-17
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
